version: "3"

services:
  app:
    container_name: "app"
    build: ./play
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: always

  server:
    container_name: "server"
    build: ./server
    ports:
      - "8081:80"
    environment:
      DB_HOST: "mysqldb"
      DB_PORT: 3306
      DB_USER: "admin"
      DB_PASSWORD: "passwd"
      DB_NAME: "cards"
    depends_on:
      - db
      - proxy
    restart: always

  proxy:
    container_name: "proxy"
    build: ./proxy
    ports:
      - "8082:8082"
    restart: always

  db:
    container_name: "mysqldb"
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "passwd"
      MYSQL_ROOT_PASSWORD: "passwd"
      MYSQL_DATABASE: "cards"
    volumes:
      - ./db/data:/var/lib/mysql/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always