<?php
//Models

//Get new player
function new_player($pid,$name,
                    $score = 0,$rank = 0,$previous_rank = 0,$gives = false,$fold = false,$can_revolution = false,$cards = array()){
    return array(
        PID=>$pid,
        NAME=>$name,
        SCORE=>$score,
        RANK=>$rank,
        PREVIOUS_RANK=>$previous_rank,
        GIVES=>$gives,
        FOLD=>$fold,
        CAN_REVOLUTION=>$can_revolution,
        CARDS=>$cards
    );
}

//Get new game
function new_game($gid,
                  $game_count = 0,$turn = 0,$sequence = 0,$last_put = -1,$state = WAIT_TO_START,$previous_players_count = 0,
                  $revolution = false,$amount = 0,$stack = array(),$PREVIOUS_CARDS_PUT = array(),$players = array()){
    return array(
        GID=>$gid,
        GAME_COUNT=>$game_count,
        TURN=>$turn,
        SEQUENCE=>$sequence,
        LAST_PUT=>$last_put,
        STATE=>$state,
        PREVIOUS_PLAYERS_COUNT=>$previous_players_count,
        REVOLUTION=>$revolution,
        AMOUNT=>$amount,
        STACK=>$stack,
        PREVIOUS_CARDS_PUT=>$PREVIOUS_CARDS_PUT,
        PLAYERS=>$players
    );
}

//All cards
$all_cards = array(
    //carreaux
    array(
        TYPE=>DIAMONDS,
        NUMBER=>1
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>2
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>3
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>4
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>5
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>6
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>7
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>8
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>9
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>10
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>11
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>12
    ),
    array(
        TYPE=>DIAMONDS,
        NUMBER=>13
    ),

    //coeurs
    array(
        TYPE=>HEARTS,
        NUMBER=>1
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>2
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>3
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>4
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>5
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>6
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>7
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>8
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>9
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>10
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>11
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>12
    ),
    array(
        TYPE=>HEARTS,
        NUMBER=>13
    ),

    //pics
    array(
        TYPE=>SPADES,
        NUMBER=>1
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>2
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>3
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>4
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>5
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>6
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>7
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>8
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>9
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>10
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>11
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>12
    ),
    array(
        TYPE=>SPADES,
        NUMBER=>13
    ),

    //trefles
    array(
        TYPE=>CLUBS,
        NUMBER=>1
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>2
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>3
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>4
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>5
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>6
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>7
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>8
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>9
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>10
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>11
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>12
    ),
    array(
        TYPE=>CLUBS,
        NUMBER=>13
    )
);